/*
 * @Author: fyh
 * @Date: 2020-01-04 17:37:27
 * @Desc: 模拟后端返回菜单数据
 */

export default {
  code: 200,
  msg: "成功",
  data: [
    {
      permissionId: "ACTIVATION_CODE_MD",
      permissionName: "激活码管理",
      parentId: null,
      menuIcon: "el-icon-document-copy",
      menuPath: "/cdkey",
    },
    {
      permissionId: "RECOMMEND_CODE_MD",
      permissionName: "推荐码管理",
      parentId: null,
      menuIcon: "el-icon-document-copy",
      menuPath: "/recommendationcode",
    },
    {
      permissionId: "MEMBER_MGMT_MD",
      permissionName: "会员管理",
      parentId: null,
      menuIcon: "el-icon-user",
      menuPath: "/member/list",
      children: [],
    },
    {
      permissionId: "TRACKING_MD",
      permissionName: "回访管理",
      parentId: null,
      menuIcon: "el-icon-notebook-2",
      menuPath: "/revisit",
    },
    {
      permissionId: "MEMBER_IM_MD",
      permissionName: "即时沟通",
      parentId: null,
      menuIcon: "el-icon-s-commen",
      menuPath: "/communicate",
    },
    {
      permissionId: "EXPERT_CONSULT_MD222",
      permissionName: "申请管理",
      parentId: null,
      menuIcon: "el-icon-s-custom",
      menuPath: "/apply",
      children: [
        {
          permissionId: "EXPERT_CONSULT_MD",
          permissionName: "专家咨询申请",
          parentId: null,
          menuIcon: "el-icon-s-custom",
          menuPath: "/apply/expert",
        },
        {
          permissionId: "REPORTING_SERVICES_MD",
          permissionName: "报告服务申请",
          parentId: null,
          menuIcon: "el-icon-copy-document",
          menuPath: "/apply/report",
        },
        {
          permissionId: "VALUE_ADD_SERVICES_MD",
          permissionName: "增值服务申请",
          parentId: null,
          menuIcon: "el-icon-tickets",
          menuPath: "/apply/value",
        },
      ],
    },
    {
      permissionId: "MEMBER_RULE_MD",
      permissionName: "会员规则管理",
      parentId: null,
      menuIcon: "el-icon-more-outline",
      menuPath: "/rule",
    },
    {
      permissionId: "AD_MD_ACTIVITY",
      permissionName: "活动管理",
      parentId: "AD_MD",
      menuIcon: null,
      menuPath: "/activity",
      children: null,
    },
    {
      permissionId: "DATA_STAT_MD",
      permissionName: "数据统计",
      parentId: null,
      menuIcon: "el-icon-s-data",
      menuPath: "/count",
      children: [
        {
          permissionId: "DATA_STAT_MD_MEMBER",
          permissionName: "用户统计",
          parentId: "DATA_STAT_MD",
          menuIcon: null,
          menuPath: "/count/member",
          children: null,
        },
        {
          permissionId: "DATA_STAT_MD_SERVICE",
          permissionName: "服务统计",
          parentId: "DATA_STAT_MD",
          menuIcon: null,
          menuPath: "/count/service",
          children: null,
        },
        {
          permissionId: "DATA_STAT_MD_SERVICE_PERFORMANCE",
          permissionName: "绩效统计",
          parentId: "DATA_STAT_MD",
          menuIcon: null,
          menuPath: "/count/performance",
          children: null,
        },
      ],
    },
    {
      permissionId: "AD_MD",
      permissionName: "广告管理",
      parentId: null,
      menuIcon: "el-icon-goods",
      menuPath: "/ad",
      children: [
        {
          permissionId: "AD_MD_ACTIVITY",
          permissionName: "活动管理",
          parentId: "AD_MD",
          menuIcon: null,
          menuPath: "/activity",
          children: null,
        },
        {
          permissionId: "AD_MD_ROTATION_IMAGES",
          permissionName: "轮播图管理",
          parentId: "AD_MD",
          menuIcon: null,
          menuPath: "/rotationImg",
          children: null,
        },
      ],
    },
    {
      children: [],
      controlPermissions: null,
      dataPermissions: null,
      menuIcon: "el-icon-document",
      menuPath: "/article",
      parentId: null,
      permissionId: "ARTICLE_MD",
      permissionName: "文章管理",
      tagPageChilden: [],
    },
    {
      permissionId: "BUSINESS_BASIC_DATA_MD",
      permissionName: "业务基础数据管理",
      parentId: null,
      menuIcon: "el-icon-receiving",
      menuPath: "/business",
      children: [
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_SERVICES_PACKAGE",
          permissionName: "服务套餐管理",
          parentId: "BUSINESS_BASIC_DATA_MD",
          menuIcon: null,
          menuPath: "/business/package",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_VALUE_ADD_SERVICE",
          permissionName: "增值服务管理",
          parentId: "BUSINESS_BASIC_DATA_MD",
          menuIcon: null,
          menuPath: "/business/value",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_TAG",
          permissionName: "通用标签管理",
          parentId: "BUSINESS_BASIC_DATA_MD",
          menuIcon: "el-icon-collection-tag",
          menuPath: "/business/tag",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_APPLETWEEKLYDATA",
          permissionName: "小程序数据统计",
          parentId: "BUSINESS_BASIC_DATA_MD",
          menuIcon: null,
          menuPath: "/business/appletWeeklyData",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_CLINICSTATISTICSDATA",
          permissionName: "诊所周数据统计",
          parentId: "BUSINESS_BASIC_DATA_MD",
          menuIcon: null,
          menuPath: "/business/clinicStatisticsData",
          children: null,
        },
      ],
    },
    {
      permissionId: "SYS_MGMT_MD",
      permissionName: "系统管理",
      parentId: null,
      menuIcon: "el-icon-setting",
      menuPath: "/system",
      children: [
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_SERVICES_PACKAGE",
          permissionName: "工作人员管理",
          parentId: "SYS_MGMT_MD",
          menuIcon: null,
          menuPath: "/system/staff",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_VALUE_ADD_SERVICE",
          permissionName: "系统日志审计",
          parentId: "SYS_MGMT_MD",
          menuIcon: null,
          menuPath: "/system/log",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_TAG",
          permissionName: "系统参数管理",
          parentId: "SYS_MGMT_MD",
          menuIcon: "el-icon-collection-tag",
          menuPath: "/system/param",
          children: null,
        },
        {
          permissionId: "BUSINESS_BASIC_DATA_MD_TAG",
          permissionName: "角色和权限",
          parentId: "SYS_MGMT_MD",
          menuIcon: "el-icon-collection-tag",
          menuPath: "/system/permissions",
          children: null,
        },
        //tag-menu
        // {
        //   permissionId: "SYS_MENU_MD",
        //   permissionName: "菜单配置",
        //   parentId: "SYS_MGMT_MD",
        //   menuIcon: "el-icon-news",
        //   menuPath: "/system/menumanagement",
        //   children: null,
        // },
      ],
    },
    {
      permissionId: "MESSAGE_CENTER_MD",
      permissionName: "消息中心",
      parentId: null,
      menuIcon: "el-icon-chat-dot-square",
      menuPath: "/message",
      children: [],
    },
  ],
};
